import exceptions

# ['ArithmeticError', 'AssertionError'.....]
#print(dir(exceptions))